SHELL := /bin/bash
all:
	$(MAKE) -C util
	$(MAKE) -C hsssec
	$(MAKE) -C hss
	$(MAKE) -C hssgtw

clean:
	$(MAKE) -C util clean
	$(MAKE) -C hsssec clean
	$(MAKE) -C hss clean
	$(MAKE) -C hssgtw clean

#install:
#	$(MAKE) -C c3poutil install
